<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tujuan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tujuan_model');
         $this->load->library('session'); 
        if(!$this->session->has_userdata('nama_adminn')){
            redirect('home/login');   
        }
    } 

    /*
     * Listing of tujuan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tujuan/index?');
        $config['total_rows'] = $this->Tujuan_model->get_all_tujuan_count();
        $this->pagination->initialize($config);

        $data['tujuan'] = $this->Tujuan_model->get_all_tujuan($params);
        
        $data['_view'] = 'tujuan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tujuan
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nama','Nama','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
            );
            
            $tujuan_id = $this->Tujuan_model->add_tujuan($params);
            redirect('tujuan/index');
        }
        else
        {            
            $data['_view'] = 'tujuan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tujuan
     */
    function edit($id)
    {   
        // check if the tujuan exists before trying to edit it
        $data['tujuan'] = $this->Tujuan_model->get_tujuan($id);
        
        if(isset($data['tujuan']['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nama','Nama','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
                );

                $this->Tujuan_model->update_tujuan($id,$params);            
                redirect('tujuan/index');
            }
            else
            {
                $data['_view'] = 'tujuan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tujuan you are trying to edit does not exist.');
    } 

    /*
     * Deleting tujuan
     */
    function remove($id)
    {
        $tujuan = $this->Tujuan_model->get_tujuan($id);

        // check if the tujuan exists before trying to delete it
        if(isset($tujuan['id']))
        {
            $this->Tujuan_model->delete_tujuan($id);
            redirect('tujuan/index');
        }
        else
            show_error('The tujuan you are trying to delete does not exist.');
    }
    
}
