<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tujuan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tujuan by id
     */
    function get_tujuan($id)
    {
        return $this->db->get_where('tujuan',array('id'=>$id))->row_array();
    }
    
    /*
     * Get all tujuan count
     */
    function get_all_tujuan_count()
    {
        $this->db->from('tujuan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all tujuan
     */
    function get_all_tujuan($params = array())
    {
        $this->db->order_by('id', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('tujuan')->result_array();
    }
        
    /*
     * function to add new tujuan
     */
    function add_tujuan($params)
    {
        $this->db->insert('tujuan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tujuan
     */
    function update_tujuan($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('tujuan',$params);
    }
    
    /*
     * function to delete tujuan
     */
    function delete_tujuan($id)
    {
        return $this->db->delete('tujuan',array('id'=>$id));
    }
}
